# Generated by Django 3.2.9 on 2022-01-04 11:27

from django.db import migrations, models
import loginApp.password_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255, validators=[loginApp.password_validator.password_custome_validate.NumberValidator.validate, loginApp.password_validator.password_custome_validate.SymbolValidator.validate, loginApp.password_validator.password_custome_validate.LowercaseValidator.validate, loginApp.password_validator.password_custome_validate.UppercaseValidator.validate])),
                ('email', models.CharField(max_length=100)),
                ('history', models.CharField(max_length=62)),
            ],
            options={
                'db_table': 'loginapp_user',
            },
        ),
        migrations.CreateModel(
            name='SeasonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
    ]
