# Generated by Django 3.2.9 on 2022-01-04 12:46

from django.db import migrations, models
import loginApp.password_validator


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, validators=[loginApp.password_validator.password_custome_validate.NumberValidator.validate, loginApp.password_validator.password_custome_validate.SymbolValidator.validate, loginApp.password_validator.password_custome_validate.LowercaseValidator.validate, loginApp.password_validator.password_custome_validate.UppercaseValidator.validate]),
        ),
    ]
